// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BootstrapSessions() {
  return window['go']['main']['App']['BootstrapSessions']();
}

export function ClearApiKey() {
  return window['go']['main']['App']['ClearApiKey']();
}

export function CreateSession() {
  return window['go']['main']['App']['CreateSession']();
}

export function DeleteSession(arg1) {
  return window['go']['main']['App']['DeleteSession'](arg1);
}

export function EnsurePreviewServer() {
  return window['go']['main']['App']['EnsurePreviewServer']();
}

export function GetActiveSessionID() {
  return window['go']['main']['App']['GetActiveSessionID']();
}

export function GetApiKey() {
  return window['go']['main']['App']['GetApiKey']();
}

export function GetPreviewPort() {
  return window['go']['main']['App']['GetPreviewPort']();
}

export function GetPreviewStatus() {
  return window['go']['main']['App']['GetPreviewStatus']();
}

export function GetSessionPRD(arg1) {
  return window['go']['main']['App']['GetSessionPRD'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function KillPreviewServer() {
  return window['go']['main']['App']['KillPreviewServer']();
}

export function ListSessions() {
  return window['go']['main']['App']['ListSessions']();
}

export function LoadSession(arg1) {
  return window['go']['main']['App']['LoadSession'](arg1);
}

export function RenameSession(arg1, arg2) {
  return window['go']['main']['App']['RenameSession'](arg1, arg2);
}

export function SaveApiKey(arg1) {
  return window['go']['main']['App']['SaveApiKey'](arg1);
}

export function SaveMessages(arg1, arg2) {
  return window['go']['main']['App']['SaveMessages'](arg1, arg2);
}

export function SaveSessionPRD(arg1, arg2) {
  return window['go']['main']['App']['SaveSessionPRD'](arg1, arg2);
}

export function SaveSessionPreview(arg1, arg2) {
  return window['go']['main']['App']['SaveSessionPreview'](arg1, arg2);
}

export function WriteGeneratedCode(arg1) {
  return window['go']['main']['App']['WriteGeneratedCode'](arg1);
}

export function WriteMockData(arg1) {
  return window['go']['main']['App']['WriteMockData'](arg1);
}
