// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function BootstrapSessions():Promise<main.SessionData>;

export function ClearApiKey():Promise<void>;

export function CreateSession():Promise<main.SessionMeta>;

export function DeleteSession(arg1:string):Promise<void>;

export function EnsurePreviewServer():Promise<number>;

export function GetActiveSessionID():Promise<string>;

export function GetApiKey():Promise<string>;

export function GetPreviewPort():Promise<number>;

export function GetPreviewStatus():Promise<string>;

export function GetSessionPRD(arg1:string):Promise<string>;

export function GetSidebarCollapsed():Promise<boolean>;

export function Greet(arg1:string):Promise<string>;

export function KillPreviewServer():Promise<void>;

export function ListSessions():Promise<Array<main.SessionMeta>>;

export function LoadSession(arg1:string):Promise<main.SessionData>;

export function RenameSession(arg1:string,arg2:string):Promise<void>;

export function SaveApiKey(arg1:string):Promise<void>;

export function SaveMessages(arg1:string,arg2:Array<main.ChatMessage>):Promise<void>;

export function SaveSessionPRD(arg1:string,arg2:string):Promise<void>;

export function SaveSessionPreview(arg1:string,arg2:string):Promise<void>;

export function SetSidebarCollapsed(arg1:boolean):Promise<void>;

export function WriteGeneratedCode(arg1:string):Promise<void>;

export function WriteMockData(arg1:string):Promise<void>;
